### ISSUE TITLE
Add templates apart from files

### ISSUE THREAD

**Issue by metalmatze** [kubeciio/kubectl#1]
Files work like this, but they don't support templating.
```yaml
pipeline:
  kubectl:
    image: kubeciio/kubectl
    kubectl: get namespaces
    files:
    - foo.yaml
    - bar.yaml
```

Lets add templates which run through Go's `text/template` first and are then used as normal files by kubectl.
```yaml
pipeline:
  kubectl:
    image: kubeciio/kubectl
    kubectl: get namespaces
    templates:
    - foo.yaml
    - bar.yaml
```
